### ISSUE TITLE
New architecture: Reboot UIEffectCapturedImage

### ISSUE THREAD

**Issue by mob-sakai** [mob-sakai/UIEffect#184]
UIEffectCapturedImage has many bugs.
To fix those bugs, UIEffectCapturedImage will be separated into another repository.
* [x] Create new repository
  * [ ] Transfer the issues about `UIEffectCapturedImage`
* [ ] Support Metal and Vulkan graphic API
  * [ ] Mipmap blurring
  * https://docs.unity3d.com/ScriptReference/Rendering.CopyTextureSupport.html
    >Metal and WebGL currently do not have texture copy support
* [ ] Use ScreenCapture.CaptureScreenshotIntoRenderTexture to capture screen
  * [ ] Support Unity 2018 or later
* [x] Remove `UIEffectCapturedImage` from this project

**Comment by mob-sakai** [comment]
This is an alternative package to `UICaptureEffect` component. (in preview)
https://github.com/mob-sakai/UIEffectSnapshot

Please note that the API may change until stable release.
